let n = {
  Description: "SME16434",
  CustomerID: "C112313                       ",
  LocationID: "MAIN      ",
  ServiceContractID: "AHS00003330",
  CustomerContractID: "CPPAHS77  ",
  EquipmentDescription: "Achieva",
  SerialNbr: "22286",
  Status: "Active",
  Room: null,
  SoftwareRelease: null,
  SystemIPAddress: "172.16.19.67",
  Modality: "MRI",
  ModelDescription: "Achieva",
  CustomerName: "UT Health East Olympic Center",
  LocationName: "Primary Location",
  AddressLine1: "700 Olympic Circle",
  AddressLine2: null,
  City: "Tyler",
  State: "TX",
  PostalCode: "75701",
  Model: "ACHIEVA 1.5T",
  CustomerUniqueID: null,
  Manufacturer: "Philips Medical Systems",
  LastPMCompleted: null,
  PMFrequencyinmonths: null,
  LegacyEquipmentID: null,
  ShowonRemoteServicesWebsite: null,
  ServiceContractCustomerID: "C112313                       ",
  ServiceContractCustomerName: "UT Health East Olympic Center",
  CustomerContractCustomerID: "C0151                         ",
  CustomerContractCustomerName: "Renovo Solutions, LLC",
  ServiceContractStatus: "Active",
  CustomerContractStatus: "Active",
  ServiceContractLocationID: "MAIN      ",
  ServiceContractLocationName: "Primary Location",
  CustomerContractLocationID: "SHIP073   ",
  CustomerContractLocationName: "UT Health East Texas Physicians",
  ExpirationDate: "2026-02-28T00:00:00",
  MMBControlNumber: null,
  IGAHCreated: "2023-03-31T18:34:29.22",
  IGAHCreatedBy: "angela.schwartz",
  IGAHUpdatedBy: "michelle.brock",
  IGAHUpdated: "2024-04-11T16:01:02.82",
  IGAHActive: true,
  RemoteConnectivityImplemeted: true,
  PrimaryEngineer: null,
  PrimaryEngineer_2: "LORTIZ                        ",
  EmployeeName: "Ortiz, Luis",
  SecondaryEngineer: null,
  SecondaryEngineer_2: null,
  EmployeeName_2: null,
  Workgroup: "Dallas",
  BAWorkgroup: "Dallas",
  RemoteCoverage: "RMM",
  SCDesc:
    "CPPAHS77 - Magnet Monitoring - Monday-Sunday - 24 Hours (Exp 2/28/26)",
  HostImplementationDate: "2023-10-06T00:00:00",
  RTTNotes: null,
  SiteID: "CE# 36541 / Philips ID: 42919096",
  SiteID_2: null,
  RemoteConnectivityStatus: "Implemented",
  AccountID: 172599,
  ManufacturerID: "PHILIPS        ",
  Model_2: "ACHIEVA 1.5T",
  AddressID: 787151,
  ManufacturerID_2: "PHILIPS        ",
  EntityType: "Contract",
  ContractID: 4724,
  ServiceContractID_2: "AHS00003330",
  EquipmentID: "SME16434",
  AccountID_2: "C112313                       ",
  CustomerID_2: "C112313                       ",
  EquipmentNbr: "SME16434",
  Login: "russ.gregory"
};
